### ISSUE TITLE
Unable to open Relax in gui

### ISSUE THREAD

**Issue by kyleeast13** [compbiocore/nmrdock#5]
```
Traceback (most recent call last):
  File "/home/ubuntu/relax-4.1.1/multi/processor.py", line 494, in run
    self.callback.init_master(self)
  File "/home/ubuntu/relax-4.1.1/multi/__init__.py", line 318, in default_init_master
    self.master.run()
  File "/home/ubuntu/relax-4.1.1/relax.py", line 203, in run
    import gui
  File "/home/ubuntu/relax-4.1.1/gui/__init__.py", line 39, in <module>
    from gui.uf_objects import Uf_storage; uf_store = Uf_storage()
  File "/home/ubuntu/relax-4.1.1/gui/uf_objects.py", line 35, in <module>
    from gui.components.free_file_format import Free_file_format
  File "/home/ubuntu/relax-4.1.1/gui/components/free_file_format.py", line 31, in <module>
    from gui.icons import relax_icons
  File "/home/ubuntu/relax-4.1.1/gui/icons.py", line 46, in <module>
    relax_icons = Relax_icons()
PyNoAppError: The wx.App object must be created first!
```

**Comment by kyleeast13** [comment]
Apparently a bug fix in 4.1.2.
```
relax GUI: wxPython-Phoenix 4.x fix to allow relax to start again. In the later wxPython versions, relax would not be able to start either the GUI or any of the test suite due to a new error "wx._core.PyNoAppError: The wx.App object must be created first!". This was not present in wxPython-Phoenix 3. The Relax_icons class (a wx.IconBundle derived class) is no longer instantiated on import.
```

**Comment by kyleeast13** [comment]
After updating to 4.1.3, a new issue arose: 
```
14:54:23: Debug: Adding duplicate image handler for 'Windows bitmap file'
Traceback (most recent call last):
  File "/home/ubuntu/relax-4.1.3/gui/__init__.py", line 100, in OnInit
    self.gui = relax_gui.Main(parent=None, id=-1, title="")
  File "/home/ubuntu/relax-4.1.3/gui/relax_gui.py", line 132, in __init__
    relax_icons.setup()
  File "/home/ubuntu/relax-4.1.3/gui/icons.py", line 42, in setup
    self.AddIconFromFile(status.install_path + sep + 'graphics' + sep + 'ulysses.ico', wx.BITMAP_TYPE_ANY)
AttributeError: 'Relax_icons' object has no attribute 'AddIconFromFile'
OnInit returned false, exiting...
```

It appears that this is due to wxPython. 
```
The problem is that relax currently does not support the unstable
wxPython-Phoenix versions of wxPython.  I have development branches in
the source code repository dealing with this, but the relax releases
do not.  Specifically because wxPython-Phoenix is not stable and is
changing, and some features used by relax are completely missing (for
now).  You need to use wxPython classic - i.e. versions < 4.0.

Note however that with the upcoming relax 4.1.2 release, I have fixed
the error you see.  There will be significant other issues though if
you continue using wxPython >= 4.0.
```
